### ISSUE TITLE
Rename properties to something coherent

### ISSUE THREAD

**Issue by LeoNatan** [sovata8/RevealingTableViewCell#4]
What is `uiView_revealedContent_left`? Why not `leftView`?
Same for the other names.

Do those names look like anything from UIKit to you? When creating frameworks to be used in iOS, you should strive to give similar patterns and naming conventions as Apple's iOS frameworks.

**Comment by sovata8** [comment]
Thanks for raising this issue.

I agree that there are many reasons why the currently chosen names (`uiView_mainContent` etc.) are not great.
- too long
- contain underscores
- start with redundant information (the type of the property)
- do not follow 'natural word order' (e.g. 'view left' vs. 'left view')
- not consistent with UIKIt / Cocoa Touch.

However for my projects I have come to prefer this style of naming, for various reasons, including the fact that all my IBOutlets (or subview properties) sort together by type in auto-complete lists and in interface builder. I have my justification for the underscore and the overly descriptive names too, but not sure if I should go into all these details in this message.

I understand I should strive to follow conventions and naming styles and why that's important. And I do it most of the time, unless there is a situation where I feel the benefits of 'breaking' the established style outweigh the drawbacks. This is one such situation.

Of course I am always open to changing my mind on this (being persuaded otherwise), but for now I will close the issue.
