### ISSUE TITLE
Disable when < iOS10 instead of the strict DeploymentTarget

### ISSUE THREAD

**Issue by Jaspur** [sovata8/RevealingTableViewCell#7]
Hi @sovata8 , my App *needs* iOS9 support, but because of this package I can set the Deployment target to lower then iOS10. 

For this Module I already implemented:
```
@available(iOS 10, *)
// use RevealingTableViewCell things
```
But it's not working, because of this error:
![schermafdruk 2017-11-13 15 45 40_preview](https://user-images.githubusercontent.com/4254854/32731306-bd947eee-c889-11e7-900c-d7102bf59293.png)
> Module file's minimum deployment target is ios10.0 v10.0

**Comment by sovata8** [comment]
Hi,

The required minimum iOS is iOS 10, as mentioned in the installation section. I am not planning to make it compatible with anything lower than this.

I am not completely sure what you mean by "Disable when < iOS10 instead of the strict DeploymentTarget". The point of `RevealingTableViewCell` is to be subclassed - is it even possible to conditionally subclass using `@available` (and how would you do this just in Interface Builder)? And I am pretty sure I have to set a `DeploymentTarget` to something. Setting it lower (but not actually implementing it) is not a good idea. Let me know if I am missing something here. Thanks.

**Comment by Jaspur** [comment]
Got it to work on iOS 9 :-)  Even on iOS 8 it's working now :P Just some little tweaks in your code needed.

**Comment by sovata8** [comment]
OK, I am closing this issue then. Maybe for anyone else having the same requirements, provide an explanation how you did it, or a link to your fork. Thanks.
